### ISSUE TITLE
Add functionality to find out dependencies and reverse dependencies (direct and transitive)

### ISSUE THREAD

**Issue by cournape** [enthought/sat-solver#171]
In the buildsystem, we currently rely on the following features derived from the old enstaller dependency solver:

1. Given a recipe (i.e. here a package name and its exact version), and a set of packages `S`, which subset of `S` depends on the recipe. E.g. you have the recipe for `numpy 1.10.3-2`, you want to find out which packages from `S` on that exact version of numpy. You want to find out either direct dependencies, or transitive ones. Usecase: when you update a package, say numpy, you want to have the set of packages that need testing to validate the new version is good.
2. Given a recipe and a set of packages `S`, which packages in `S` are dependencies of the recipe.

For both 1 and 2, we also want relaxed constraint on the recipe. The typical use case is when we update the version of a package (say numpy from `1.9.2` to `1.10.4`), we need to find every package that used to depend on `numpy 1.9.2`.

@johntyree, @noraderam  does that make sense ?

**Comment by cournape** [comment]
So a bit more details, with some examples.

Let's say I have the following recipes:

```
# @ build N means the recipe, when built, produces an egg with version `<upstream version>-<build>`
MKL-11.1.4/ # no dependency, @ build 1
numpy-1.9.2/ # depends on `MKL ^= 11.1.4`, @ build 2
scipy-0.17.0/ # depends on `MKL ^= 11.1.4` and `numpy ^= 1.9.2`, @ build 1
```

Assuming I have converted those recipes into dummy package metadata with the corresponding dependencies, used them to populate a `Pool` instance, we need something that looks as follows:

``` python
def compute_reverse_dependencies(pool, package, transitive=False):
    """ Compute the set of every package in the given pool that depends on the given package

    Parameters
    ----------------
    pool : Pool
    package : PackageMetadata
        the package to look reverse dependencies for
    transitive : bool
        If True, recursively walk up the dependency graph. If False (default), only returns the packages
        that directly depend on the package.

    Returns
    -----------
    reverse_dependencies : sequence
        Set of packages in the pool that depends on the given package
    """
   ...

mkl = PackageMetadata(...) # assumed to be populated correctly by the API user
# reverse_dependencies should contain both scipy and numpy package metadata
reverse_dependencies = compute_reverse_dependencies(pool, mkl)
```

Unless prohibitively slow, that does not need to be very fast (e.g. taking ~ 1 sec for a repository with a few hundred of packages is fine).

**Comment by cournape** [comment]
Actually, it may make sense to use a `requirement` instead of a `package` in `compute_reverse_dependencies`, to easily support the usecase where we want to know every package that depends on `numpy`, not just `numpy 1.9.2-2`.

As for existing code, there is some graph-related utilities in `simplesat.utils.graph`. I am not very familiar with that code myself, so if you don't find what you need, we can arrange to look at it together.

**Comment by johntyree** [comment]
There is also a function to get all transitive dependencies, given a
package dependency graph. That should be all you need to answer this
question.

**Comment by noraderam** [comment]
I've run into some difficulties constructing a full package dependency graph. `package_lit_dependency_graph` takes a `pool` and a collection of package literals. The graph is constructed only of these packages and their immediate dependencies. To obtain the full graph, we need to know all of the available packages, but there is no means to get this information from the `pool`.

Options:

1. Add a mechanism to obtain packages from the `pool`. This could be done directly or by providing a method to iterate over `repositories`, which could then be used to iterate over their constituent packages.
2. Write a new graph building function which includes chained dependencies
3. Change the proposed function signature for `compute_reverse_dependencies` to accept a collection of `repositories` rather than a `pool`. This may or may not be practical based on how we intend to use the function.

Initial discussion took place on [Slack](https://enthought.slack.com/archives/jaguar/p1459446308000110)

**Comment by cournape** [comment]
3 sounds like the simplest, right ? If we see the need to iterate of packages in a pool in another context, we may want to implement 1.

**Comment by noraderam** [comment]
> 3 sounds like the simplest, right ?

Yes, as long as it's reasonable to expect callers to have access to `repositories`

**Comment by cournape** [comment]
That should be fine. I can't think of many cases where one would have access to a pool without repositories.
