### ISSUE TITLE
#71 breaks upgrade cases

### ISSUE THREAD

**Issue by cournape** [enthought/sat-solver#73]
Thinking more about it, the fix in #71 is not correct, as it allows the solver to remove any installed package.

I think we should put the rules back in, and fix the remove case differently. To see an example of a broken scenario, you can look at the `epd_full_scenario.yaml`, and notice how many installed packages are removed.

**Comment by johntyree** [comment]
I was just looking at that myself. We definitely can't put the rules back in as they were because they explicitly require that the solution includes all of the originally installed packages. No strategy for removing them will be able to work around that.

I was hoping to have a clever flash of insight about it today.

**Comment by johntyree** [comment]
If packages are suggested in the right order, this will not happen. #65 doesn't have this problem, for example.

I'll take a look at the original `UndeterminedClausePolicy` today and see why it isn't suggesting packages in the order we want.

**Comment by cournape** [comment]
@johntyree longer term, part of the solution may be to treat separately "packages installed explicitly" from "packages installed as dependencies". But we do not track this information now :(

**Comment by johntyree** [comment]
Yes we'll definitely need to do that if this is going to make sense, but that's at a different level really. I would think that the goal is something like, "Packages installed explicitly *must* remain installed, while packages installed implicitly should not be changed unless necessary." Right now it looks like we're getting, "Packages not installed explicitly during this operation are removed," which is never going to work :)

**Comment by cournape** [comment]
indeed, hence why I mentioned "part of the solution" ;)

**Comment by johntyree** [comment]
OK. I've spent a long time trying all sorts of clever tricks to sort this out and it is clear that we have no choice but to incorporate the notion of "explicitly" vs "implicitly" installed packages for this to work, and even then there's a difference between explicitly installed `pandas` vs explicitly installed `pandas 0.15.1`. In the former case, we should be free to shuffle versions around to meet new requirements as long as some version of pandas remains installed, whereas the latter case is really "pinning" in the traditional sense.

The previous method of adding rules for `pool.what_provides(<pandas>)` achieved the former, but since we aren't actually tracking it, it is being applied to all packages.

**Comment by johntyree** [comment]
We've discussed the idea of having "marked" packages now. I think it will be enough to apply the previous `pool.what_provides(to_requirement(<pkg>))` rules for all marked packages and then proceed as usual.

Pinning will be handled the same way, although the UX will be likely be quite different around it.

**Comment by johntyree** [comment]
@cournape does #83 satisfy this? I think any package that isn't marked should be fair game to be uninstalled.

**Comment by cournape** [comment]
Yes.
